### ISSUE TITLE
Using `export` raises an error 

### ISSUE THREAD

**Issue by wallace11** [docspell/dsc#112]
Hi,
Using `export --all` option gave me the following error: `Error creating a file: Filename too long (os error 36)` (taken from the rust backtrace).
Using amd64 v0.6.1 on Linux.

**Comment by eikek** [comment]
Thanks for the report, this occurred recently for someone else in eikek/docspell#1350. 

What filesystem are you using here? I'm wondering (as I wrote in the other issue) how that can happen, because all names in the database are capped to a length of 254 and from my memory I thought most filesystems today can hold filenames with 255 characters. Do you have an idea what document could cause this?

**Comment by wallace11** [comment]
The first try was actually on a tmpfs, but since then I tried it on an ext4 over NFS as well as on a local ext4.
It tripped over a filename that had a space in it - maybe that could serve as a clue?

**Comment by eikek** [comment]
This is probably due to umlauts (or other non-ascii chars) in the original filename. Described at https://github.com/eikek/docspell/issues/1350#issuecomment-1072069219
